### ISSUE TITLE
Kanban board -review

### ISSUE THREAD

**Issue by farouqdaif1** [farouqdaif1/space-travelers-hub#21]
- link for the project: https://github.com/farouqdaif1/space-travelers-hub/projects/1
- we are two in this project

**Comment by dasileker** [comment]
### **Hi @farouqdaif1,** 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

- The project card should be17 since you are two.

![Capture web_20-12-2021_15146_gitlab com](https://user-images.githubusercontent.com/61562626/146780666-399ac78b-80d7-43b5-aee7-2c7d0670641c.jpeg)
![Capture web_20-12-2021_151340_github com](https://user-images.githubusercontent.com/61562626/146780671-4d88338c-f639-4d8e-a9d0-0b821d060263.jpeg)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by farouqdaif1** [comment]
Hey Mr @dasileker  but it should be 13, not 17 ??

**Comment by dasileker** [comment]
> Hey, thanks for the review  Mr @dasileker  but it should be 13, not 17 ??

It's 17th cards, i attached a screen shot

**Comment by farouqdaif1** [comment]
> > Hey, thanks for the review  Mr @dasileker  but it should be 13, not 17 ??
> 
> It's 17th cards, i attached a screen shot

thanks @dasileker I fix the problem

**Comment by elyor-doniyorov** [comment]
Hi @farouqdaif1 and @Lichapa, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
